// socketio-react/src/App.js
import './App.css';
import React, {useEffect, useState, useRef} from 'react';
import {
	initiateSocketConnection,
	disconnectSocket,
  sendMessage,
  subscribeToMessages,
} from "./socketio.service";

// static data only for demo purposes, in real world scenario, this would be already stored on client
const SENDER = {
  id: '123',
  name: "John Doe"
};

function App() {
  const CHAT_ROOM = 'myRandomChatRoomId';

  const [token, setToken] = useState('');
  const [messages, setMessages] = useState([]);

  const tokenInputRef = useRef('');
  const inputRef = useRef('');

  useEffect(() => {
    if (token) {
      initiateSocketConnection(token);
      subscribeToMessages((err, data) => {
        console.log(data);
        setMessages(prev => [...prev, data]);
      });
      return () => {
        disconnectSocket();
      }
    }
  }, [token]);

  const submitToken = (e) => {
    e.preventDefault();
    const tokenValue = tokenInputRef.current.value;
    setToken(tokenValue);
  }

  const submitMessage = (e) => {
    e.preventDefault();
    const message = inputRef.current.value;
    sendMessage({message, roomName: CHAT_ROOM}, cb => {
      // callback is acknowledgement from server
      console.log(cb);
      setMessages(prev => [...prev, {
          message,
          ...SENDER
        }]
      );
      // clear the input after the message is sent
      inputRef.current.value = '';
    });
  }

  return (
    <div className="App">
      <form onSubmit={submitToken}>
        <input type="text" placeholder="Enter token" ref={tokenInputRef} />
        <button type="submit">Submit</button>
      </form>
      {/* <button onClick={() => joinChatRoom()}>Join Room</button> */}
      <div className="box">
        <div className="messages">
          {messages.map((user, index) => <div key={index}>{user.name}: {user.message}</div>)}
        </div>
        <form className="input-div" onSubmit={submitMessage}>
          <input type="text" placeholder="Type in text" ref={inputRef} />
          <button type="submit">Submit</button>
        </form>
      </div>
    </div>
  );
}

export default App;

// socketio-angular/src/app/app.component.ts
import { SocketioService } from './socketio.service';
import { Component, OnInit } from '@angular/core';
import { FormBuilder } from '@angular/forms';

// static data only for demo purposes, in real world scenario, this would be already stored on client
const SENDER = {
  id: "123",
  name: "John Doe",
};
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})

export class AppComponent implements OnInit {
  title = 'socketio-angular';

  CHAT_ROOM = "myRandomChatRoomId";

  messages = [];

  tokenForm = this.formBuilder.group({
    token: '',
  });

  messageForm = this.formBuilder.group({
    message: '',
  });

  constructor(private socketService: SocketioService, private formBuilder: FormBuilder) {}

  ngOnInit() {
  }

  submitToken() {
    const token = this.tokenForm.get('token').value;
    if (token) {
      this.socketService.setupSocketConnection(token);
      this.socketService.subscribeToMessages((err, data) => {
        console.log("NEW MESSAGE ", data);
        this.messages = [...this.messages, data];
      });
    }
  }

  submitMessage() {
    const message = this.messageForm.get('message').value;
    if (message) {
      this.socketService.sendMessage({message, roomName: this.CHAT_ROOM}, cb => {
        console.log("ACKNOWLEDGEMENT ", cb);
      });
      this.messages = [
        ...this.messages,
        {
          message,
          ...SENDER,
        },
      ];
      // clear the input after the message is sent
      this.messageForm.reset();
    }
  }
  
  ngOnDestroy() {
    this.socketService.disconnect();
  }
}

<div class="App">
  <form [formGroup]="tokenForm" (submit)="submitToken()">
    <input type="text" placeholder="Enter token" formControlName="token" />
    <button type="submit">Submit</button>
  </form>
  <div class="box">
    <div class="messages">
      <div *ngFor="let user of messages">
        {{user.name}}: {{user.message}}
      </div>
    </div>
    <form [formGroup]="messageForm" class="input-div" (submit)="submitMessage()">
      <input type="text" placeholder="Type in text" formControlName="message" />
      <button type="submit">Send</button>
    </form>
  </div>
</div>
